const birthdayData = {
  students: [
    { name: "구준모", month: 4, day: 9, note: "" },
    { name: "구준혁", month: 11, day: 27, note: "" },
    { name: "김규민", month: 7, day: 17, note: "" },
    { name: "김노아", month: 10, day: 4, note: "" },
    { name: "김도원", month: 10, day: 2, note: "" },
    { name: "김준수", month: 6, day: 29, note: "" },
    { name: "김지완", month: 7, day: 4, note: "" },
    { name: "김채윤", month: 1, day: 21, note: "" },
    { name: "박세하", month: 10, day: 9, note: "" },
    { name: "배민성", month: 5, day: 23, note: "" },
    { name: "송지민", month: 3, day: 29, note: "" },
    { name: "신지아", month: 3, day: 13, note: "" },
    { name: "양승우", month: 9, day: 7, note: "" },
    { name: "양연우", month: 1, day: 14, note: "" },
    { name: "오세준", month: 9, day: 2, note: "" },
    { name: "우솔별", month: 11, day: 19, note: "" },
    { name: "원혜빈", month: 10, day: 28, note: "" },
    { name: "유민아", month: 11, day: 26, note: "" },
    { name: "이가연", month: 1, day: 24, note: "" },
    { name: "이지은", month: 3, day: 2, note: "" },
    { name: "임선미", month: 4, day: 23, note: "" },
    { name: "전수민", month: 8, day: 20, note: "" },
    { name: "정성원", month: 12, day: 2, note: "" },
    { name: "정재환", month: 2, day: 18, note: "" },
    { name: "조우현", month: 11, day: 15, note: "" },
    { name: "최소율", month: 12, day: 12, note: "" },
    { name: "최예나", month: 10, day: 11, note: "" },
    { name: "한승지", month: 2, day: 13, note: "" },
  ],

  teachers: [
    {
      name: "서민우",
      month: 4,
      day: 10,
      note: "",
    },
  ],
};
